# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'
 use_frameworks!
target 'SinaWeibo_swift' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  

  # Pods for SinaWeibo_swift
pod  'AFNetworking'
pod  'SDWebImage'
pod  'SVProgressHUD'
#pod  'SnapKit~0.22.0'
pod  'SnapKit', '~> 3.0'

end
