# Uncomment this line to define a global platform for your project


platform :ios, '9.0'
 use_frameworks!
target 'SinaWeibo_swift' do

pod  'AFNetworking'
pod  'SDWebImage'
pod  'SVProgressHUD'
pod  'SnapKit', '0.19.0'
pod  'MJRefresh'
end
